name: Week Clean

on:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call the Clean API Endpoint
        run: |
          curl -X GET https://cutiefly-sid.vercel.app/api/clean
